// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rest.proto

package rest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestFieldOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Gorm            string                 `protobuf:"bytes,1,opt,name=gorm,proto3" json:"gorm,omitempty"`
	Comment         string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Scenarios       string                 `protobuf:"bytes,3,opt,name=scenarios,proto3" json:"scenarios,omitempty"`
	Position        string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Format          string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Props           string                 `protobuf:"bytes,6,opt,name=props,proto3" json:"props,omitempty"`
	Rule            string                 `protobuf:"bytes,7,opt,name=rule,proto3" json:"rule,omitempty"`
	Live            string                 `protobuf:"bytes,8,opt,name=live,proto3" json:"live,omitempty"`
	Dropdown        string                 `protobuf:"bytes,9,opt,name=dropdown,proto3" json:"dropdown,omitempty"`
	Enum            string                 `protobuf:"bytes,10,opt,name=enum,proto3" json:"enum,omitempty"`
	Match           string                 `protobuf:"bytes,11,opt,name=match,proto3" json:"match,omitempty"`
	Invisible       string                 `protobuf:"bytes,12,opt,name=invisible,proto3" json:"invisible,omitempty"`
	Tooltip         string                 `protobuf:"bytes,13,opt,name=tooltip,proto3" json:"tooltip,omitempty"`
	Uploaduri       string                 `protobuf:"bytes,14,opt,name=uploaduri,proto3" json:"uploaduri,omitempty"`
	Description     string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	Readonly        string                 `protobuf:"bytes,16,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Endofnow        string                 `protobuf:"bytes,17,opt,name=endofnow,proto3" json:"endofnow,omitempty"`
	Condition       string                 `protobuf:"bytes,18,opt,name=condition,proto3" json:"condition,omitempty"`
	Timesearchrange string                 `protobuf:"bytes,19,opt,name=timesearchrange,proto3" json:"timesearchrange,omitempty"`
	Label           string                 `protobuf:"bytes,20,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestFieldOptions) Reset() {
	*x = RestFieldOptions{}
	mi := &file_rest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestFieldOptions) ProtoMessage() {}

func (x *RestFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestFieldOptions.ProtoReflect.Descriptor instead.
func (*RestFieldOptions) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{0}
}

func (x *RestFieldOptions) GetGorm() string {
	if x != nil {
		return x.Gorm
	}
	return ""
}

func (x *RestFieldOptions) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RestFieldOptions) GetScenarios() string {
	if x != nil {
		return x.Scenarios
	}
	return ""
}

func (x *RestFieldOptions) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *RestFieldOptions) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RestFieldOptions) GetProps() string {
	if x != nil {
		return x.Props
	}
	return ""
}

func (x *RestFieldOptions) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *RestFieldOptions) GetLive() string {
	if x != nil {
		return x.Live
	}
	return ""
}

func (x *RestFieldOptions) GetDropdown() string {
	if x != nil {
		return x.Dropdown
	}
	return ""
}

func (x *RestFieldOptions) GetEnum() string {
	if x != nil {
		return x.Enum
	}
	return ""
}

func (x *RestFieldOptions) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *RestFieldOptions) GetInvisible() string {
	if x != nil {
		return x.Invisible
	}
	return ""
}

func (x *RestFieldOptions) GetTooltip() string {
	if x != nil {
		return x.Tooltip
	}
	return ""
}

func (x *RestFieldOptions) GetUploaduri() string {
	if x != nil {
		return x.Uploaduri
	}
	return ""
}

func (x *RestFieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestFieldOptions) GetReadonly() string {
	if x != nil {
		return x.Readonly
	}
	return ""
}

func (x *RestFieldOptions) GetEndofnow() string {
	if x != nil {
		return x.Endofnow
	}
	return ""
}

func (x *RestFieldOptions) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *RestFieldOptions) GetTimesearchrange() string {
	if x != nil {
		return x.Timesearchrange
	}
	return ""
}

func (x *RestFieldOptions) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RestMessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Scenarios     []string               `protobuf:"bytes,4,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestMessageOptions) Reset() {
	*x = RestMessageOptions{}
	mi := &file_rest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestMessageOptions) ProtoMessage() {}

func (x *RestMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestMessageOptions.ProtoReflect.Descriptor instead.
func (*RestMessageOptions) Descriptor() ([]byte, []int) {
	return file_rest_proto_rawDescGZIP(), []int{1}
}

func (x *RestMessageOptions) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RestMessageOptions) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RestMessageOptions) GetScenarios() []string {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var file_rest_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*RestFieldOptions)(nil),
		Field:         52118,
		Name:          "aeus.field",
		Tag:           "bytes,52118,opt,name=field",
		Filename:      "rest.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*RestMessageOptions)(nil),
		Field:         52119,
		Name:          "aeus.rest",
		Tag:           "bytes,52119,opt,name=rest",
		Filename:      "rest.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// ormable will cause orm code to be generated for this field
	//
	// optional aeus.RestFieldOptions field = 52118;
	E_Field = &file_rest_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// ormable will cause orm code to be generated for this message/object
	//
	// optional aeus.RestMessageOptions rest = 52119;
	E_Rest = &file_rest_proto_extTypes[1]
)

var File_rest_proto protoreflect.FileDescriptor

const file_rest_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rest.proto\x12\x04aeus\x1a google/protobuf/descriptor.proto\"\xa4\x04\n" +
	"\x10RestFieldOptions\x12\x12\n" +
	"\x04gorm\x18\x01 \x01(\tR\x04gorm\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1c\n" +
	"\tscenarios\x18\x03 \x01(\tR\tscenarios\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x14\n" +
	"\x05props\x18\x06 \x01(\tR\x05props\x12\x12\n" +
	"\x04rule\x18\a \x01(\tR\x04rule\x12\x12\n" +
	"\x04live\x18\b \x01(\tR\x04live\x12\x1a\n" +
	"\bdropdown\x18\t \x01(\tR\bdropdown\x12\x12\n" +
	"\x04enum\x18\n" +
	" \x01(\tR\x04enum\x12\x14\n" +
	"\x05match\x18\v \x01(\tR\x05match\x12\x1c\n" +
	"\tinvisible\x18\f \x01(\tR\tinvisible\x12\x18\n" +
	"\atooltip\x18\r \x01(\tR\atooltip\x12\x1c\n" +
	"\tuploaduri\x18\x0e \x01(\tR\tuploaduri\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12\x1a\n" +
	"\breadonly\x18\x10 \x01(\tR\breadonly\x12\x1a\n" +
	"\bendofnow\x18\x11 \x01(\tR\bendofnow\x12\x1c\n" +
	"\tcondition\x18\x12 \x01(\tR\tcondition\x12(\n" +
	"\x0ftimesearchrange\x18\x13 \x01(\tR\x0ftimesearchrange\x12\x14\n" +
	"\x05label\x18\x14 \x01(\tR\x05label\"`\n" +
	"\x12RestMessageOptions\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x1c\n" +
	"\tscenarios\x18\x04 \x03(\tR\tscenarios:M\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x96\x97\x03 \x01(\v2\x16.aeus.RestFieldOptionsR\x05field:O\n" +
	"\x04rest\x12\x1f.google.protobuf.MessageOptions\x18\x97\x97\x03 \x01(\v2\x18.aeus.RestMessageOptionsR\x04restB)Z'github.com:sjlit/aeus/pkg/proto/restb\x06proto3"

var (
	file_rest_proto_rawDescOnce sync.Once
	file_rest_proto_rawDescData []byte
)

func file_rest_proto_rawDescGZIP() []byte {
	file_rest_proto_rawDescOnce.Do(func() {
		file_rest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rest_proto_rawDesc), len(file_rest_proto_rawDesc)))
	})
	return file_rest_proto_rawDescData
}

var file_rest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rest_proto_goTypes = []any{
	(*RestFieldOptions)(nil),            // 0: aeus.RestFieldOptions
	(*RestMessageOptions)(nil),          // 1: aeus.RestMessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_rest_proto_depIdxs = []int32{
	2, // 0: aeus.field:extendee -> google.protobuf.FieldOptions
	3, // 1: aeus.rest:extendee -> google.protobuf.MessageOptions
	0, // 2: aeus.field:type_name -> aeus.RestFieldOptions
	1, // 3: aeus.rest:type_name -> aeus.RestMessageOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rest_proto_init() }
func file_rest_proto_init() {
	if File_rest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rest_proto_rawDesc), len(file_rest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_rest_proto_goTypes,
		DependencyIndexes: file_rest_proto_depIdxs,
		MessageInfos:      file_rest_proto_msgTypes,
		ExtensionInfos:    file_rest_proto_extTypes,
	}.Build()
	File_rest_proto = out.File
	file_rest_proto_goTypes = nil
	file_rest_proto_depIdxs = nil
}
