// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: auth.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// AuthService implements the login lifecycle: password login, refresh
// token exchange, and logout (token revocation).
type AuthServiceHttpServer interface {
	// Authenticates uid/username + password and issues an access token
	// (TTL default 2h) plus a refresh token (48h).
	// Wire format: POST /auth/login.
	Login(ctx context.Context, req *LoginRequest) (res *LoginResponse, err error)
	// Exchanges a valid refresh token for a fresh access token without
	// rotating the refresh token.
	// Wire format: POST /auth/refresh-token.
	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (res *RefreshTokenResponse, err error)
	// Revokes the access token in the TokenStore and returns the uid of
	// the ended session.
	// Wire format: POST /auth/logout.
	Logout(ctx context.Context, req *LogoutRequest) (res *LogoutResponse, err error)
}

// AuthService server wrapper
type AuthServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server AuthServiceHttpServer
}

func (s *AuthServiceServerWrapper) wrapHttpAuthServiceLogin(ctx *http.Context) (err error) {
	req := &LoginRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.Login(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *AuthServiceServerWrapper) wrapHttpAuthServiceRefreshToken(ctx *http.Context) (err error) {
	req := &RefreshTokenRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.RefreshToken(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *AuthServiceServerWrapper) wrapHttpAuthServiceLogout(ctx *http.Context) (err error) {
	req := &LogoutRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.Logout(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterAuthServiceRouter(hs *http.Server, s AuthServiceHttpServer, opts ...http.RouteOption) {
	is := &AuthServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register AuthService.Login http handler
	hs.POST("/auth/login", is.wrapHttpAuthServiceLogin)
	// register AuthService.RefreshToken http handler
	hs.POST("/auth/refresh-token", is.wrapHttpAuthServiceRefreshToken)
	// register AuthService.Logout http handler
	hs.POST("/auth/logout", is.wrapHttpAuthServiceLogout)
}
