// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: menu.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MenuTreeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MenuTreeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuTreeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MenuTreeResponseMultiError, or nil if none found.
func (m *MenuTreeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuTreeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuTreeResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenuTreeResponseMultiError(errors)
	}

	return nil
}

// MenuTreeResponseMultiError is an error wrapping multiple validation errors
// returned by MenuTreeResponse.ValidateAll() if the designated constraints
// aren't met.
type MenuTreeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuTreeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuTreeResponseMultiError) AllErrors() []error { return m }

// MenuTreeResponseValidationError is the validation error returned by
// MenuTreeResponse.Validate if the designated constraints aren't met.
type MenuTreeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuTreeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuTreeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuTreeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuTreeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuTreeResponseValidationError) ErrorName() string { return "MenuTreeResponseValidationError" }

// Error satisfies the builtin error interface
func (e MenuTreeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuTreeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuTreeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuTreeResponseValidationError{}

// Validate checks the field values on MenuNode with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuNode) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuNode with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuNodeMultiError, or nil
// if none found.
func (m *MenuNode) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuNode) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Title

	// no validation rules for Component

	// no validation rules for Uri

	// no validation rules for Icon

	// no validation rules for Hidden

	// no validation rules for Public

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuNodeValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuNodeValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuNodeValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenuNodeMultiError(errors)
	}

	return nil
}

// MenuNodeMultiError is an error wrapping multiple validation errors returned
// by MenuNode.ValidateAll() if the designated constraints aren't met.
type MenuNodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuNodeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuNodeMultiError) AllErrors() []error { return m }

// MenuNodeValidationError is the validation error returned by
// MenuNode.Validate if the designated constraints aren't met.
type MenuNodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuNodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuNodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuNodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuNodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuNodeValidationError) ErrorName() string { return "MenuNodeValidationError" }

// Error satisfies the builtin error interface
func (e MenuNodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuNode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuNodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuNodeValidationError{}

// Validate checks the field values on MenuItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuItemMultiError, or nil
// if none found.
func (m *MenuItem) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Parent

	// no validation rules for Name

	// no validation rules for Component

	// no validation rules for Uri

	// no validation rules for ViewPath

	// no validation rules for Icon

	// no validation rules for Hidden

	// no validation rules for Public

	// no validation rules for Sort

	// no validation rules for Description

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return MenuItemMultiError(errors)
	}

	return nil
}

// MenuItemMultiError is an error wrapping multiple validation errors returned
// by MenuItem.ValidateAll() if the designated constraints aren't met.
type MenuItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuItemMultiError) AllErrors() []error { return m }

// MenuItemValidationError is the validation error returned by
// MenuItem.Validate if the designated constraints aren't met.
type MenuItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuItemValidationError) ErrorName() string { return "MenuItemValidationError" }

// Error satisfies the builtin error interface
func (e MenuItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuItemValidationError{}

// Validate checks the field values on MenuListAllResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MenuListAllResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuListAllResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MenuListAllResponseMultiError, or nil if none found.
func (m *MenuListAllResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuListAllResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuListAllResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuListAllResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuListAllResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenuListAllResponseMultiError(errors)
	}

	return nil
}

// MenuListAllResponseMultiError is an error wrapping multiple validation
// errors returned by MenuListAllResponse.ValidateAll() if the designated
// constraints aren't met.
type MenuListAllResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuListAllResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuListAllResponseMultiError) AllErrors() []error { return m }

// MenuListAllResponseValidationError is the validation error returned by
// MenuListAllResponse.Validate if the designated constraints aren't met.
type MenuListAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuListAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuListAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuListAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuListAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuListAllResponseValidationError) ErrorName() string {
	return "MenuListAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MenuListAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuListAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuListAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuListAllResponseValidationError{}

// Validate checks the field values on MenuOptionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MenuOptionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuOptionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MenuOptionsResponseMultiError, or nil if none found.
func (m *MenuOptionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuOptionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuOptionsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenuOptionsResponseMultiError(errors)
	}

	return nil
}

// MenuOptionsResponseMultiError is an error wrapping multiple validation
// errors returned by MenuOptionsResponse.ValidateAll() if the designated
// constraints aren't met.
type MenuOptionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuOptionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuOptionsResponseMultiError) AllErrors() []error { return m }

// MenuOptionsResponseValidationError is the validation error returned by
// MenuOptionsResponse.Validate if the designated constraints aren't met.
type MenuOptionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuOptionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuOptionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuOptionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuOptionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuOptionsResponseValidationError) ErrorName() string {
	return "MenuOptionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MenuOptionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuOptionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuOptionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuOptionsResponseValidationError{}

// Validate checks the field values on OptionNode with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OptionNode) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OptionNode with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OptionNodeMultiError, or
// nil if none found.
func (m *OptionNode) ValidateAll() error {
	return m.validate(true)
}

func (m *OptionNode) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Label

	// no validation rules for Parent

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OptionNodeValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OptionNodeValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OptionNodeValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OptionNodeMultiError(errors)
	}

	return nil
}

// OptionNodeMultiError is an error wrapping multiple validation errors
// returned by OptionNode.ValidateAll() if the designated constraints aren't met.
type OptionNodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OptionNodeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OptionNodeMultiError) AllErrors() []error { return m }

// OptionNodeValidationError is the validation error returned by
// OptionNode.Validate if the designated constraints aren't met.
type OptionNodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptionNodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptionNodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptionNodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptionNodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptionNodeValidationError) ErrorName() string { return "OptionNodeValidationError" }

// Error satisfies the builtin error interface
func (e OptionNodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOptionNode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptionNodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptionNodeValidationError{}

// Validate checks the field values on MenuBreadcrumbRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MenuBreadcrumbRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuBreadcrumbRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MenuBreadcrumbRequestMultiError, or nil if none found.
func (m *MenuBreadcrumbRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuBreadcrumbRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() < 1 {
		err := MenuBreadcrumbRequestValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return MenuBreadcrumbRequestMultiError(errors)
	}

	return nil
}

// MenuBreadcrumbRequestMultiError is an error wrapping multiple validation
// errors returned by MenuBreadcrumbRequest.ValidateAll() if the designated
// constraints aren't met.
type MenuBreadcrumbRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuBreadcrumbRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuBreadcrumbRequestMultiError) AllErrors() []error { return m }

// MenuBreadcrumbRequestValidationError is the validation error returned by
// MenuBreadcrumbRequest.Validate if the designated constraints aren't met.
type MenuBreadcrumbRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuBreadcrumbRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuBreadcrumbRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuBreadcrumbRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuBreadcrumbRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuBreadcrumbRequestValidationError) ErrorName() string {
	return "MenuBreadcrumbRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MenuBreadcrumbRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuBreadcrumbRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuBreadcrumbRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuBreadcrumbRequestValidationError{}

// Validate checks the field values on MenuBreadcrumbResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MenuBreadcrumbResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuBreadcrumbResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MenuBreadcrumbResponseMultiError, or nil if none found.
func (m *MenuBreadcrumbResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuBreadcrumbResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MenuBreadcrumbResponseMultiError(errors)
	}

	return nil
}

// MenuBreadcrumbResponseMultiError is an error wrapping multiple validation
// errors returned by MenuBreadcrumbResponse.ValidateAll() if the designated
// constraints aren't met.
type MenuBreadcrumbResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuBreadcrumbResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuBreadcrumbResponseMultiError) AllErrors() []error { return m }

// MenuBreadcrumbResponseValidationError is the validation error returned by
// MenuBreadcrumbResponse.Validate if the designated constraints aren't met.
type MenuBreadcrumbResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuBreadcrumbResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuBreadcrumbResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuBreadcrumbResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuBreadcrumbResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuBreadcrumbResponseValidationError) ErrorName() string {
	return "MenuBreadcrumbResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MenuBreadcrumbResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuBreadcrumbResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuBreadcrumbResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuBreadcrumbResponseValidationError{}
