// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: menu.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// MenuService exposes the admin menu manager's read endpoints.
type MenuServiceHttpServer interface {
	// Full menu tree of all menus, including hidden and public ones; the
	// admin menu manager's read endpoint.
	// Wire format: GET /menu/tree.
	MenuTree(ctx context.Context, req *Empty) (res *MenuTreeResponse, err error)
	// Menu cascader options (value = Menu.Component, usable directly as
	// Menu.Parent).  Wire format: GET /menu/options.
	MenuOptions(ctx context.Context, req *Empty) (res *MenuOptionsResponse, err error)
	// Breadcrumb: the Component chain from the node to the root.
	// Wire format: GET /menu/breadcrumb?id={id} — transport/http's ctx.Bind
	// binds the id from the query string. The annotation deliberately
	// omits the query part: protoc-gen-go-aeus emits the template
	// verbatim and gin treats "?" as a literal path char (dead route).
	MenuBreadcrumb(ctx context.Context, req *MenuBreadcrumbRequest) (res *MenuBreadcrumbResponse, err error)
}

// MenuService server wrapper
type MenuServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server MenuServiceHttpServer
}

func (s *MenuServiceServerWrapper) wrapHttpMenuServiceMenuTree(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.MenuTree(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *MenuServiceServerWrapper) wrapHttpMenuServiceMenuOptions(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.MenuOptions(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *MenuServiceServerWrapper) wrapHttpMenuServiceMenuBreadcrumb(ctx *http.Context) (err error) {
	req := &MenuBreadcrumbRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.MenuBreadcrumb(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterMenuServiceRouter(hs *http.Server, s MenuServiceHttpServer, opts ...http.RouteOption) {
	is := &MenuServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register MenuService.MenuTree http handler
	hs.GET("/menu/tree", is.wrapHttpMenuServiceMenuTree)
	// register MenuService.MenuOptions http handler
	hs.GET("/menu/options", is.wrapHttpMenuServiceMenuOptions)
	// register MenuService.MenuBreadcrumb http handler
	hs.GET("/menu/breadcrumb", is.wrapHttpMenuServiceMenuBreadcrumb)
}
