// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: menu.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MenuTreeResponse carries the root-level MenuNode items; children
// nest the full tree.
type MenuTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuNode            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeResponse) Reset() {
	*x = MenuTreeResponse{}
	mi := &file_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeResponse) ProtoMessage() {}

func (x *MenuTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeResponse.ProtoReflect.Descriptor instead.
func (*MenuTreeResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuTreeResponse) GetItems() []*MenuNode {
	if x != nil {
		return x.Items
	}
	return nil
}

// MenuNode is one menu row plus its children. component mirrors
// models.Menu.Component (also what Menu.Parent references); hidden and
// public mirror the row flags.
type MenuNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Public        bool                   `protobuf:"varint,7,opt,name=public,proto3" json:"public,omitempty"`
	Children      []*MenuNode            `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuNode) Reset() {
	*x = MenuNode{}
	mi := &file_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuNode) ProtoMessage() {}

func (x *MenuNode) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuNode.ProtoReflect.Descriptor instead.
func (*MenuNode) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{1}
}

func (x *MenuNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuNode) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuNode) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MenuNode) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuNode) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MenuNode) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *MenuNode) GetChildren() []*MenuNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// MenuOptionsResponse carries cascader options; value is the
// Menu.Component, usable directly as Menu.Parent (see MenuOptions).
type MenuOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OptionNode          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuOptionsResponse) Reset() {
	*x = MenuOptionsResponse{}
	mi := &file_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuOptionsResponse) ProtoMessage() {}

func (x *MenuOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuOptionsResponse.ProtoReflect.Descriptor instead.
func (*MenuOptionsResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{2}
}

func (x *MenuOptionsResponse) GetItems() []*OptionNode {
	if x != nil {
		return x.Items
	}
	return nil
}

// OptionNode is one cascader tier: value = Menu.Component,
// label = Menu.Name, parent = the parent's Component.
type OptionNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Children      []*OptionNode          `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionNode) Reset() {
	*x = OptionNode{}
	mi := &file_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionNode) ProtoMessage() {}

func (x *OptionNode) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionNode.ProtoReflect.Descriptor instead.
func (*OptionNode) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{3}
}

func (x *OptionNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *OptionNode) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *OptionNode) GetChildren() []*OptionNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// MenuBreadcrumbRequest selects the menu whose Component chain to
// the root is returned.
type MenuBreadcrumbRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuBreadcrumbRequest) Reset() {
	*x = MenuBreadcrumbRequest{}
	mi := &file_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuBreadcrumbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuBreadcrumbRequest) ProtoMessage() {}

func (x *MenuBreadcrumbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuBreadcrumbRequest.ProtoReflect.Descriptor instead.
func (*MenuBreadcrumbRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{4}
}

func (x *MenuBreadcrumbRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// MenuBreadcrumbResponse carries the Component chain from the node
// to the root.
type MenuBreadcrumbResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component chain to root (breadcrumb). Field name kept for wire
	// stability; "path" here is the component chain, not Menu.uri.
	Path          []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuBreadcrumbResponse) Reset() {
	*x = MenuBreadcrumbResponse{}
	mi := &file_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuBreadcrumbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuBreadcrumbResponse) ProtoMessage() {}

func (x *MenuBreadcrumbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuBreadcrumbResponse.ProtoReflect.Descriptor instead.
func (*MenuBreadcrumbResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{5}
}

func (x *MenuBreadcrumbResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_menu_proto protoreflect.FileDescriptor

const file_menu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"menu.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"6\n" +
	"\x10MenuTreeResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.pb.MenuNodeR\x05items\"\xd2\x01\n" +
	"\bMenuNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\x12\x16\n" +
	"\x06public\x18\a \x01(\bR\x06public\x12(\n" +
	"\bchildren\x18\b \x03(\v2\f.pb.MenuNodeR\bchildren\";\n" +
	"\x13MenuOptionsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.pb.OptionNodeR\x05items\"|\n" +
	"\n" +
	"OptionNode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12*\n" +
	"\bchildren\x18\x04 \x03(\v2\x0e.pb.OptionNodeR\bchildren\"0\n" +
	"\x15MenuBreadcrumbRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02(\x01R\x02id\",\n" +
	"\x16MenuBreadcrumbResponse\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path2\x95\x02\n" +
	"\vMenuService\x12L\n" +
	"\bMenuTree\x12\x16.google.protobuf.Empty\x1a\x14.pb.MenuTreeResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/menu/tree\x12U\n" +
	"\vMenuOptions\x12\x16.google.protobuf.Empty\x1a\x17.pb.MenuOptionsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/menu/options\x12a\n" +
	"\x0eMenuBreadcrumb\x12\x19.pb.MenuBreadcrumbRequest\x1a\x1a.pb.MenuBreadcrumbResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/menu/breadcrumbB#Z!github.com/sjlit/aeus/admin/pb;pbb\x06proto3"

var (
	file_menu_proto_rawDescOnce sync.Once
	file_menu_proto_rawDescData []byte
)

func file_menu_proto_rawDescGZIP() []byte {
	file_menu_proto_rawDescOnce.Do(func() {
		file_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)))
	})
	return file_menu_proto_rawDescData
}

var file_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_menu_proto_goTypes = []any{
	(*MenuTreeResponse)(nil),       // 0: pb.MenuTreeResponse
	(*MenuNode)(nil),               // 1: pb.MenuNode
	(*MenuOptionsResponse)(nil),    // 2: pb.MenuOptionsResponse
	(*OptionNode)(nil),             // 3: pb.OptionNode
	(*MenuBreadcrumbRequest)(nil),  // 4: pb.MenuBreadcrumbRequest
	(*MenuBreadcrumbResponse)(nil), // 5: pb.MenuBreadcrumbResponse
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_menu_proto_depIdxs = []int32{
	1, // 0: pb.MenuTreeResponse.items:type_name -> pb.MenuNode
	1, // 1: pb.MenuNode.children:type_name -> pb.MenuNode
	3, // 2: pb.MenuOptionsResponse.items:type_name -> pb.OptionNode
	3, // 3: pb.OptionNode.children:type_name -> pb.OptionNode
	6, // 4: pb.MenuService.MenuTree:input_type -> google.protobuf.Empty
	6, // 5: pb.MenuService.MenuOptions:input_type -> google.protobuf.Empty
	4, // 6: pb.MenuService.MenuBreadcrumb:input_type -> pb.MenuBreadcrumbRequest
	0, // 7: pb.MenuService.MenuTree:output_type -> pb.MenuTreeResponse
	2, // 8: pb.MenuService.MenuOptions:output_type -> pb.MenuOptionsResponse
	5, // 9: pb.MenuService.MenuBreadcrumb:output_type -> pb.MenuBreadcrumbResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_menu_proto_init() }
func file_menu_proto_init() {
	if File_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_depIdxs,
		MessageInfos:      file_menu_proto_msgTypes,
	}.Build()
	File_menu_proto = out.File
	file_menu_proto_goTypes = nil
	file_menu_proto_depIdxs = nil
}
