// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: permission.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// PermissionService exposes the global permission catalog
// (sys_permissions).
type PermissionServiceHttpServer interface {
	// Lists the global permission catalog (sys_permissions), optionally
	// filtered by type.
	// Wire format: GET /permission/catalog?type={0|1|2|3|4}.
	ListCatalog(ctx context.Context, req *ListCatalogRequest) (res *ListCatalogResponse, err error)
}

// PermissionService server wrapper
type permissionServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server PermissionServiceHttpServer
}

func (s *permissionServiceServerWrapper) wrapHttpPermissionServiceListCatalog(ctx *http.Context) (err error) {
	req := &ListCatalogRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.ListCatalog(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterPermissionServiceRouter(hs *http.Server, s PermissionServiceHttpServer, opts ...http.RouteOption) {
	is := &permissionServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register PermissionService.ListCatalog http handler
	hs.GET("/permission/catalog", is.wrapHttpPermissionServiceListCatalog)
}
