// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: permission.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PermissionType discriminates the permission catalog entries and the
// role-permission queries.
type PermissionType int32

const (
	PermissionType_PERMISSION_TYPE_UNSPECIFIED PermissionType = 0
	PermissionType_PERMISSION_TYPE_MENU        PermissionType = 1
	PermissionType_PERMISSION_TYPE_API         PermissionType = 2
	// Catalog types (see models.PermissionType).  Appended in 2026-08-07;
	// wire-safe: existing values 0-2 are unchanged.
	PermissionType_PERMISSION_TYPE_BUTTON     PermissionType = 3
	PermissionType_PERMISSION_TYPE_DATA_SCOPE PermissionType = 4
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "PERMISSION_TYPE_UNSPECIFIED",
		1: "PERMISSION_TYPE_MENU",
		2: "PERMISSION_TYPE_API",
		3: "PERMISSION_TYPE_BUTTON",
		4: "PERMISSION_TYPE_DATA_SCOPE",
	}
	PermissionType_value = map[string]int32{
		"PERMISSION_TYPE_UNSPECIFIED": 0,
		"PERMISSION_TYPE_MENU":        1,
		"PERMISSION_TYPE_API":         2,
		"PERMISSION_TYPE_BUTTON":      3,
		"PERMISSION_TYPE_DATA_SCOPE":  4,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

// ListCatalogRequest optionally filters the catalog by type;
// UNSPECIFIED (default) returns every entry.
type ListCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PermissionType         `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PermissionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogRequest) Reset() {
	*x = ListCatalogRequest{}
	mi := &file_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogRequest) ProtoMessage() {}

func (x *ListCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogRequest) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

func (x *ListCatalogRequest) GetType() PermissionType {
	if x != nil {
		return x.Type
	}
	return PermissionType_PERMISSION_TYPE_UNSPECIFIED
}

// ListCatalogResponse carries the catalog entries as permission codes
// (Permission.Data), one string per entry.
type ListCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogResponse) Reset() {
	*x = ListCatalogResponse{}
	mi := &file_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogResponse) ProtoMessage() {}

func (x *ListCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogResponse) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{1}
}

func (x *ListCatalogResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// ListPermissionItem is one full row from sys_permissions.  Field
// numbers follow the proto wire format — do not reuse 1-5 for other
// fields in this message; future revisions should append.
type ListPermissionItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data        string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Group is the UI clustering label (e.g. "审计", "用户").
	// Auto-filled from MenuEntry().Name by derive.go on Setup; empty
	// for legacy rows that pre-date the column (auto-back-filled on
	// next Setup pass).  Operators can edit freely via /system/sys_perm.
	Group         string `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionItem) Reset() {
	*x = ListPermissionItem{}
	mi := &file_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionItem) ProtoMessage() {}

func (x *ListPermissionItem) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionItem.ProtoReflect.Descriptor instead.
func (*ListPermissionItem) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{2}
}

func (x *ListPermissionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListPermissionItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListPermissionItem) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ListPermissionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListPermissionItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// ListPermissionsRequest optionally filters by Permission.Type (the
// models-layer string constant: "api", "button", "data_scope").  An
// empty type returns every row.
type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{3}
}

func (x *ListPermissionsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ListPermissionsResponse carries the full catalog rows for the
// management UI.
type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListPermissionItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{4}
}

func (x *ListPermissionsResponse) GetItems() []*ListPermissionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\x12ListCatalogRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.pb.PermissionTypeR\x04type\"+\n" +
	"\x13ListCatalogResponse\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\x84\x01\n" +
	"\x12ListPermissionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\",\n" +
	"\x16ListPermissionsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"G\n" +
	"\x17ListPermissionsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.pb.ListPermissionItemR\x05items*\xa0\x01\n" +
	"\x0ePermissionType\x12\x1f\n" +
	"\x1bPERMISSION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PERMISSION_TYPE_MENU\x10\x01\x12\x17\n" +
	"\x13PERMISSION_TYPE_API\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_TYPE_BUTTON\x10\x03\x12\x1e\n" +
	"\x1aPERMISSION_TYPE_DATA_SCOPE\x10\x042\xd6\x01\n" +
	"\x11PermissionService\x12[\n" +
	"\vListCatalog\x12\x16.pb.ListCatalogRequest\x1a\x17.pb.ListCatalogResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/permission/catalog\x12d\n" +
	"\x0fListPermissions\x12\x1a.pb.ListPermissionsRequest\x1a\x1b.pb.ListPermissionsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/permission/listB#Z!github.com/sjlit/aeus/admin/pb;pbb\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_permission_proto_goTypes = []any{
	(PermissionType)(0),             // 0: pb.PermissionType
	(*ListCatalogRequest)(nil),      // 1: pb.ListCatalogRequest
	(*ListCatalogResponse)(nil),     // 2: pb.ListCatalogResponse
	(*ListPermissionItem)(nil),      // 3: pb.ListPermissionItem
	(*ListPermissionsRequest)(nil),  // 4: pb.ListPermissionsRequest
	(*ListPermissionsResponse)(nil), // 5: pb.ListPermissionsResponse
}
var file_permission_proto_depIdxs = []int32{
	0, // 0: pb.ListCatalogRequest.type:type_name -> pb.PermissionType
	3, // 1: pb.ListPermissionsResponse.items:type_name -> pb.ListPermissionItem
	1, // 2: pb.PermissionService.ListCatalog:input_type -> pb.ListCatalogRequest
	4, // 3: pb.PermissionService.ListPermissions:input_type -> pb.ListPermissionsRequest
	2, // 4: pb.PermissionService.ListCatalog:output_type -> pb.ListCatalogResponse
	5, // 5: pb.PermissionService.ListPermissions:output_type -> pb.ListPermissionsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
		MessageInfos:      file_permission_proto_msgTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
