// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: permission.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListCatalogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCatalogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCatalogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCatalogRequestMultiError, or nil if none found.
func (m *ListCatalogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCatalogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if len(errors) > 0 {
		return ListCatalogRequestMultiError(errors)
	}

	return nil
}

// ListCatalogRequestMultiError is an error wrapping multiple validation errors
// returned by ListCatalogRequest.ValidateAll() if the designated constraints
// aren't met.
type ListCatalogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCatalogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCatalogRequestMultiError) AllErrors() []error { return m }

// ListCatalogRequestValidationError is the validation error returned by
// ListCatalogRequest.Validate if the designated constraints aren't met.
type ListCatalogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCatalogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCatalogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCatalogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCatalogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCatalogRequestValidationError) ErrorName() string {
	return "ListCatalogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCatalogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCatalogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCatalogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCatalogRequestValidationError{}

// Validate checks the field values on ListCatalogResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCatalogResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCatalogResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCatalogResponseMultiError, or nil if none found.
func (m *ListCatalogResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCatalogResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListCatalogResponseMultiError(errors)
	}

	return nil
}

// ListCatalogResponseMultiError is an error wrapping multiple validation
// errors returned by ListCatalogResponse.ValidateAll() if the designated
// constraints aren't met.
type ListCatalogResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCatalogResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCatalogResponseMultiError) AllErrors() []error { return m }

// ListCatalogResponseValidationError is the validation error returned by
// ListCatalogResponse.Validate if the designated constraints aren't met.
type ListCatalogResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCatalogResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCatalogResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCatalogResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCatalogResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCatalogResponseValidationError) ErrorName() string {
	return "ListCatalogResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCatalogResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCatalogResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCatalogResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCatalogResponseValidationError{}
