// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: role.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RolePermissionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RolePermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RolePermissionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RolePermissionsRequestMultiError, or nil if none found.
func (m *RolePermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RolePermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRole()); l < 1 || l > 60 {
		err := RolePermissionsRequestValidationError{
			field:  "Role",
			reason: "value length must be between 1 and 60 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Type

	if len(errors) > 0 {
		return RolePermissionsRequestMultiError(errors)
	}

	return nil
}

// RolePermissionsRequestMultiError is an error wrapping multiple validation
// errors returned by RolePermissionsRequest.ValidateAll() if the designated
// constraints aren't met.
type RolePermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RolePermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RolePermissionsRequestMultiError) AllErrors() []error { return m }

// RolePermissionsRequestValidationError is the validation error returned by
// RolePermissionsRequest.Validate if the designated constraints aren't met.
type RolePermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RolePermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RolePermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RolePermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RolePermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RolePermissionsRequestValidationError) ErrorName() string {
	return "RolePermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RolePermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRolePermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RolePermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RolePermissionsRequestValidationError{}

// Validate checks the field values on RolePermissionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RolePermissionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RolePermissionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RolePermissionsResponseMultiError, or nil if none found.
func (m *RolePermissionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RolePermissionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RolePermissionsResponseMultiError(errors)
	}

	return nil
}

// RolePermissionsResponseMultiError is an error wrapping multiple validation
// errors returned by RolePermissionsResponse.ValidateAll() if the designated
// constraints aren't met.
type RolePermissionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RolePermissionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RolePermissionsResponseMultiError) AllErrors() []error { return m }

// RolePermissionsResponseValidationError is the validation error returned by
// RolePermissionsResponse.Validate if the designated constraints aren't met.
type RolePermissionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RolePermissionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RolePermissionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RolePermissionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RolePermissionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RolePermissionsResponseValidationError) ErrorName() string {
	return "RolePermissionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RolePermissionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRolePermissionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RolePermissionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RolePermissionsResponseValidationError{}

// Validate checks the field values on ReplaceRolePermissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplaceRolePermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplaceRolePermissionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ReplaceRolePermissionsRequestMultiError, or nil if none found.
func (m *ReplaceRolePermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplaceRolePermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRole()); l < 1 || l > 60 {
		err := ReplaceRolePermissionsRequestValidationError{
			field:  "Role",
			reason: "value length must be between 1 and 60 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetMenus()) > 1024 {
		err := ReplaceRolePermissionsRequestValidationError{
			field:  "Menus",
			reason: "value must contain no more than 1024 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetMenus() {
		_, _ = idx, item

		if l := utf8.RuneCountInString(item); l < 1 || l > 120 {
			err := ReplaceRolePermissionsRequestValidationError{
				field:  fmt.Sprintf("Menus[%v]", idx),
				reason: "value length must be between 1 and 120 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(m.GetApis()) > 1024 {
		err := ReplaceRolePermissionsRequestValidationError{
			field:  "Apis",
			reason: "value must contain no more than 1024 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetApis() {
		_, _ = idx, item

		if l := utf8.RuneCountInString(item); l < 1 || l > 60 {
			err := ReplaceRolePermissionsRequestValidationError{
				field:  fmt.Sprintf("Apis[%v]", idx),
				reason: "value length must be between 1 and 60 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ReplaceRolePermissionsRequestMultiError(errors)
	}

	return nil
}

// ReplaceRolePermissionsRequestMultiError is an error wrapping multiple
// validation errors returned by ReplaceRolePermissionsRequest.ValidateAll()
// if the designated constraints aren't met.
type ReplaceRolePermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplaceRolePermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplaceRolePermissionsRequestMultiError) AllErrors() []error { return m }

// ReplaceRolePermissionsRequestValidationError is the validation error
// returned by ReplaceRolePermissionsRequest.Validate if the designated
// constraints aren't met.
type ReplaceRolePermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplaceRolePermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplaceRolePermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplaceRolePermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplaceRolePermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplaceRolePermissionsRequestValidationError) ErrorName() string {
	return "ReplaceRolePermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReplaceRolePermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplaceRolePermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplaceRolePermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplaceRolePermissionsRequestValidationError{}

// Validate checks the field values on ReplaceRolePermissionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplaceRolePermissionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplaceRolePermissionsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ReplaceRolePermissionsResponseMultiError, or nil if none found.
func (m *ReplaceRolePermissionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplaceRolePermissionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Role

	// no validation rules for Affected

	if len(errors) > 0 {
		return ReplaceRolePermissionsResponseMultiError(errors)
	}

	return nil
}

// ReplaceRolePermissionsResponseMultiError is an error wrapping multiple
// validation errors returned by ReplaceRolePermissionsResponse.ValidateAll()
// if the designated constraints aren't met.
type ReplaceRolePermissionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplaceRolePermissionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplaceRolePermissionsResponseMultiError) AllErrors() []error { return m }

// ReplaceRolePermissionsResponseValidationError is the validation error
// returned by ReplaceRolePermissionsResponse.Validate if the designated
// constraints aren't met.
type ReplaceRolePermissionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplaceRolePermissionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplaceRolePermissionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplaceRolePermissionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplaceRolePermissionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplaceRolePermissionsResponseValidationError) ErrorName() string {
	return "ReplaceRolePermissionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReplaceRolePermissionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplaceRolePermissionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplaceRolePermissionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplaceRolePermissionsResponseValidationError{}

// Validate checks the field values on ListRoleOptionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRoleOptionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRoleOptionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRoleOptionsResponseMultiError, or nil if none found.
func (m *ListRoleOptionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRoleOptionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRoleOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRoleOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRoleOptionsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRoleOptionsResponseMultiError(errors)
	}

	return nil
}

// ListRoleOptionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRoleOptionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRoleOptionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRoleOptionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRoleOptionsResponseMultiError) AllErrors() []error { return m }

// ListRoleOptionsResponseValidationError is the validation error returned by
// ListRoleOptionsResponse.Validate if the designated constraints aren't met.
type ListRoleOptionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRoleOptionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRoleOptionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRoleOptionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRoleOptionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRoleOptionsResponseValidationError) ErrorName() string {
	return "ListRoleOptionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRoleOptionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRoleOptionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRoleOptionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRoleOptionsResponseValidationError{}

// Validate checks the field values on OptionEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OptionEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OptionEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OptionEntryMultiError, or
// nil if none found.
func (m *OptionEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *OptionEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Label

	if len(errors) > 0 {
		return OptionEntryMultiError(errors)
	}

	return nil
}

// OptionEntryMultiError is an error wrapping multiple validation errors
// returned by OptionEntry.ValidateAll() if the designated constraints aren't met.
type OptionEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OptionEntryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OptionEntryMultiError) AllErrors() []error { return m }

// OptionEntryValidationError is the validation error returned by
// OptionEntry.Validate if the designated constraints aren't met.
type OptionEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptionEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptionEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptionEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptionEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptionEntryValidationError) ErrorName() string { return "OptionEntryValidationError" }

// Error satisfies the builtin error interface
func (e OptionEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOptionEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptionEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptionEntryValidationError{}

// Validate checks the field values on RoleMenusRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleMenusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleMenusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleMenusRequestMultiError, or nil if none found.
func (m *RoleMenusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleMenusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetRole()); l < 1 || l > 60 {
		err := RoleMenusRequestValidationError{
			field:  "Role",
			reason: "value length must be between 1 and 60 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RoleMenusRequestMultiError(errors)
	}

	return nil
}

// RoleMenusRequestMultiError is an error wrapping multiple validation errors
// returned by RoleMenusRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleMenusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleMenusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleMenusRequestMultiError) AllErrors() []error { return m }

// RoleMenusRequestValidationError is the validation error returned by
// RoleMenusRequest.Validate if the designated constraints aren't met.
type RoleMenusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleMenusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleMenusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleMenusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleMenusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleMenusRequestValidationError) ErrorName() string { return "RoleMenusRequestValidationError" }

// Error satisfies the builtin error interface
func (e RoleMenusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleMenusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleMenusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleMenusRequestValidationError{}
