// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: role.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RolePermissionsRequest selects the role whose permissions are
// read; type picks which side(s) to return (see RoleService).
type RolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// UNSPECIFIED (default) = combined; MENU / API return only that side.
	Type          PermissionType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.PermissionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsRequest) Reset() {
	*x = RolePermissionsRequest{}
	mi := &file_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsRequest) ProtoMessage() {}

func (x *RolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*RolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *RolePermissionsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolePermissionsRequest) GetType() PermissionType {
	if x != nil {
		return x.Type
	}
	return PermissionType_PERMISSION_TYPE_UNSPECIFIED
}

// RolePermissionsResponse carries the role's menus (Menu.Component
// values) and apis (Permission.Data values); only the side selected by
// type is populated.
type RolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []string               `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	Apis          []string               `protobuf:"bytes,2,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionsResponse) Reset() {
	*x = RolePermissionsResponse{}
	mi := &file_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsResponse) ProtoMessage() {}

func (x *RolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*RolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *RolePermissionsResponse) GetMenus() []string {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *RolePermissionsResponse) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

// ReplaceRolePermissionsRequest fully replaces a role's permission
// set. menus are Menu.Component values (sized 120), apis are catalog
// Permission.Data values (sized 60) — see the field rules.
type ReplaceRolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// menus are Menu.Component values, which are sized 120 in the model;
	// max_len must match (apis are catalog Permission.Data, sized 60).
	Menus         []string `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	Apis          []string `protobuf:"bytes,3,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceRolePermissionsRequest) Reset() {
	*x = ReplaceRolePermissionsRequest{}
	mi := &file_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRolePermissionsRequest) ProtoMessage() {}

func (x *ReplaceRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ReplaceRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *ReplaceRolePermissionsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ReplaceRolePermissionsRequest) GetMenus() []string {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *ReplaceRolePermissionsRequest) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

// ReplaceRolePermissionsResponse echoes the role and reports the
// number of granted permissions (len(menus) + len(apis)).
type ReplaceRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Affected      int32                  `protobuf:"varint,2,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceRolePermissionsResponse) Reset() {
	*x = ReplaceRolePermissionsResponse{}
	mi := &file_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRolePermissionsResponse) ProtoMessage() {}

func (x *ReplaceRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*ReplaceRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

func (x *ReplaceRolePermissionsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ReplaceRolePermissionsResponse) GetAffected() int32 {
	if x != nil {
		return x.Affected
	}
	return 0
}

// ListRoleOptionsResponse carries role dropdown options (key → name),
// sorted by role code.
type ListRoleOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OptionEntry         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleOptionsResponse) Reset() {
	*x = ListRoleOptionsResponse{}
	mi := &file_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleOptionsResponse) ProtoMessage() {}

func (x *ListRoleOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleOptionsResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoleOptionsResponse) GetItems() []*OptionEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// OptionEntry is a generic value/label option pair.
type OptionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionEntry) Reset() {
	*x = OptionEntry{}
	mi := &file_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionEntry) ProtoMessage() {}

func (x *OptionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionEntry.ProtoReflect.Descriptor instead.
func (*OptionEntry) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5}
}

func (x *OptionEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// RoleMenusRequest selects the role whose visible menus to preview
// (admin preview).
type RoleMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleMenusRequest) Reset() {
	*x = RoleMenusRequest{}
	mi := &file_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleMenusRequest) ProtoMessage() {}

func (x *RoleMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleMenusRequest.ProtoReflect.Descriptor instead.
func (*RoleMenusRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6}
}

func (x *RoleMenusRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_role_proto protoreflect.FileDescriptor

const file_role_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"role.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x10permission.proto\x1a\n" +
	"user.proto\"_\n" +
	"\x16RolePermissionsRequest\x12\x1d\n" +
	"\x04role\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x04role\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.pb.PermissionTypeR\x04type\"C\n" +
	"\x17RolePermissionsResponse\x12\x14\n" +
	"\x05menus\x18\x01 \x03(\tR\x05menus\x12\x12\n" +
	"\x04apis\x18\x02 \x03(\tR\x04apis\"\x8e\x01\n" +
	"\x1dReplaceRolePermissionsRequest\x12\x1d\n" +
	"\x04role\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x04role\x12'\n" +
	"\x05menus\x18\x02 \x03(\tB\x11\xfaB\x0e\x92\x01\v\x10\x80\b\"\x06r\x04\x10\x01\x18xR\x05menus\x12%\n" +
	"\x04apis\x18\x03 \x03(\tB\x11\xfaB\x0e\x92\x01\v\x10\x80\b\"\x06r\x04\x10\x01\x18<R\x04apis\"P\n" +
	"\x1eReplaceRolePermissionsResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1a\n" +
	"\baffected\x18\x02 \x01(\x05R\baffected\"@\n" +
	"\x17ListRoleOptionsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.pb.OptionEntryR\x05items\"9\n" +
	"\vOptionEntry\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"1\n" +
	"\x10RoleMenusRequest\x12\x1d\n" +
	"\x04role\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x04role2\xa8\x03\n" +
	"\vRoleService\x12e\n" +
	"\x0fRolePermissions\x12\x1a.pb.RolePermissionsRequest\x1a\x1b.pb.RolePermissionsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/role/permissions\x12}\n" +
	"\x16ReplaceRolePermissions\x12!.pb.ReplaceRolePermissionsRequest\x1a\".pb.ReplaceRolePermissionsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/role/permissions\x12]\n" +
	"\x0fListRoleOptions\x12\x16.google.protobuf.Empty\x1a\x1b.pb.ListRoleOptionsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/role/options\x12T\n" +
	"\tRoleMenus\x12\x14.pb.RoleMenusRequest\x1a\x1c.pb.ListVisibleMenusResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/role/menusB#Z!github.com/sjlit/aeus/admin/pb;pbb\x06proto3"

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData []byte
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)))
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_role_proto_goTypes = []any{
	(*RolePermissionsRequest)(nil),         // 0: pb.RolePermissionsRequest
	(*RolePermissionsResponse)(nil),        // 1: pb.RolePermissionsResponse
	(*ReplaceRolePermissionsRequest)(nil),  // 2: pb.ReplaceRolePermissionsRequest
	(*ReplaceRolePermissionsResponse)(nil), // 3: pb.ReplaceRolePermissionsResponse
	(*ListRoleOptionsResponse)(nil),        // 4: pb.ListRoleOptionsResponse
	(*OptionEntry)(nil),                    // 5: pb.OptionEntry
	(*RoleMenusRequest)(nil),               // 6: pb.RoleMenusRequest
	(PermissionType)(0),                    // 7: pb.PermissionType
	(*emptypb.Empty)(nil),                  // 8: google.protobuf.Empty
	(*ListVisibleMenusResponse)(nil),       // 9: pb.ListVisibleMenusResponse
}
var file_role_proto_depIdxs = []int32{
	7, // 0: pb.RolePermissionsRequest.type:type_name -> pb.PermissionType
	5, // 1: pb.ListRoleOptionsResponse.items:type_name -> pb.OptionEntry
	0, // 2: pb.RoleService.RolePermissions:input_type -> pb.RolePermissionsRequest
	2, // 3: pb.RoleService.ReplaceRolePermissions:input_type -> pb.ReplaceRolePermissionsRequest
	8, // 4: pb.RoleService.ListRoleOptions:input_type -> google.protobuf.Empty
	6, // 5: pb.RoleService.RoleMenus:input_type -> pb.RoleMenusRequest
	1, // 6: pb.RoleService.RolePermissions:output_type -> pb.RolePermissionsResponse
	3, // 7: pb.RoleService.ReplaceRolePermissions:output_type -> pb.ReplaceRolePermissionsResponse
	4, // 8: pb.RoleService.ListRoleOptions:output_type -> pb.ListRoleOptionsResponse
	9, // 9: pb.RoleService.RoleMenus:output_type -> pb.ListVisibleMenusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_permission_proto_init()
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
