// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: role.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// RoleService owns every role-scoped endpoint.  The generic rest/v3 CRUD
// on sys_roles covers create/update/delete/list, so this service stays
// narrow: read/replace a role's permission grants, dropdown options for
// the role picker, and admin preview of a role's visible menu tree.
//
// History: RolePermissions absorbed PermissionService.ListRolePermissions
// and RoleMenus absorbed MenuService.ListVisibleMenusByRole (both
// 2026-08-10) — every role-scoped endpoint now lives under /role/*.
type RoleServiceHttpServer interface {
	// Returns a role's permission grants (Menu.Component values in menus,
	// Permission.Data values in apis).  type UNSPECIFIED(0, default)
	// returns the combined {menus, apis}; MENU(1) returns menus only;
	// API(2) returns apis only.
	// Wire format: GET /role/permissions?role={role}[&type={0|1|2}].
	// Absorbed PermissionService.ListRolePermissions (2026-08-10).
	RolePermissions(ctx context.Context, req *RolePermissionsRequest) (res *RolePermissionsResponse, err error)
	// Fully replaces a role's permission set (see ReplaceRolePermissionsRequest):
	// existing rows for menus+apis are deleted and the new set is inserted
	// in a single transaction.
	// Wire format: PUT /role/permissions with JSON body.
	// body: "*" — role travels in the JSON body; transport/http's
	// non-GET bind is body-only (gin), a ?role= query would be ignored.
	ReplaceRolePermissions(ctx context.Context, req *ReplaceRolePermissionsRequest) (res *ReplaceRolePermissionsResponse, err error)
	// Role dropdown options (key → name) for the role picker.
	// Wire format: GET /role/options.
	ListRoleOptions(ctx context.Context, req *Empty) (res *ListRoleOptionsResponse, err error)
	// Visible menus for a specific role (admin preview — what the side
	// bar would look like for any role, not just the caller's).
	// Wire format: GET /role/menus?role={role}.
	// Moved from MenuService.ListVisibleMenusByRole (2026-08-10) so every
	// role-scoped endpoint lives under /role/*.
	RoleMenus(ctx context.Context, req *RoleMenusRequest) (res *ListVisibleMenusResponse, err error)
}

// RoleService server wrapper
type RoleServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server RoleServiceHttpServer
}

func (s *RoleServiceServerWrapper) wrapHttpRoleServiceRolePermissions(ctx *http.Context) (err error) {
	req := &RolePermissionsRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.RolePermissions(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *RoleServiceServerWrapper) wrapHttpRoleServiceReplaceRolePermissions(ctx *http.Context) (err error) {
	req := &ReplaceRolePermissionsRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.ReplaceRolePermissions(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *RoleServiceServerWrapper) wrapHttpRoleServiceListRoleOptions(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.ListRoleOptions(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *RoleServiceServerWrapper) wrapHttpRoleServiceRoleMenus(ctx *http.Context) (err error) {
	req := &RoleMenusRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.RoleMenus(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterRoleServiceRouter(hs *http.Server, s RoleServiceHttpServer, opts ...http.RouteOption) {
	is := &RoleServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register RoleService.RolePermissions http handler
	hs.GET("/role/permissions", is.wrapHttpRoleServiceRolePermissions)
	// register RoleService.ReplaceRolePermissions http handler
	hs.PUT("/role/permissions", is.wrapHttpRoleServiceReplaceRolePermissions)
	// register RoleService.ListRoleOptions http handler
	hs.GET("/role/options", is.wrapHttpRoleServiceListRoleOptions)
	// register RoleService.RoleMenus http handler
	hs.GET("/role/menus", is.wrapHttpRoleServiceRoleMenus)
}
