// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tenant.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TenantRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantRequestMultiError, or
// nil if none found.
func (m *TenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetId()); l < 1 || l > 60 {
		err := TenantRequestValidationError{
			field:  "Id",
			reason: "value length must be between 1 and 60 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TenantRequestMultiError(errors)
	}

	return nil
}

// TenantRequestMultiError is an error wrapping multiple validation errors
// returned by TenantRequest.ValidateAll() if the designated constraints
// aren't met.
type TenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantRequestMultiError) AllErrors() []error { return m }

// TenantRequestValidationError is the validation error returned by
// TenantRequest.Validate if the designated constraints aren't met.
type TenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantRequestValidationError) ErrorName() string { return "TenantRequestValidationError" }

// Error satisfies the builtin error interface
func (e TenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantRequestValidationError{}

// Validate checks the field values on TenantInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantInfoMultiError, or
// nil if none found.
func (m *TenantInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Status

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return TenantInfoMultiError(errors)
	}

	return nil
}

// TenantInfoMultiError is an error wrapping multiple validation errors
// returned by TenantInfo.ValidateAll() if the designated constraints aren't met.
type TenantInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantInfoMultiError) AllErrors() []error { return m }

// TenantInfoValidationError is the validation error returned by
// TenantInfo.Validate if the designated constraints aren't met.
type TenantInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantInfoValidationError) ErrorName() string { return "TenantInfoValidationError" }

// Error satisfies the builtin error interface
func (e TenantInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantInfoValidationError{}

// Validate checks the field values on TenantOption with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantOption with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantOptionMultiError, or
// nil if none found.
func (m *TenantOption) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return TenantOptionMultiError(errors)
	}

	return nil
}

// TenantOptionMultiError is an error wrapping multiple validation errors
// returned by TenantOption.ValidateAll() if the designated constraints aren't met.
type TenantOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantOptionMultiError) AllErrors() []error { return m }

// TenantOptionValidationError is the validation error returned by
// TenantOption.Validate if the designated constraints aren't met.
type TenantOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantOptionValidationError) ErrorName() string { return "TenantOptionValidationError" }

// Error satisfies the builtin error interface
func (e TenantOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantOptionValidationError{}

// Validate checks the field values on ListTenantOptionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTenantOptionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantOptionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantOptionsResponseMultiError, or nil if none found.
func (m *ListTenantOptionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantOptionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTenantOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTenantOptionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTenantOptionsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListTenantOptionsResponseMultiError(errors)
	}

	return nil
}

// ListTenantOptionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListTenantOptionsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListTenantOptionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantOptionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantOptionsResponseMultiError) AllErrors() []error { return m }

// ListTenantOptionsResponseValidationError is the validation error returned by
// ListTenantOptionsResponse.Validate if the designated constraints aren't met.
type ListTenantOptionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantOptionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantOptionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantOptionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantOptionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantOptionsResponseValidationError) ErrorName() string {
	return "ListTenantOptionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTenantOptionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantOptionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantOptionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantOptionsResponseValidationError{}
