// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: tenant.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// TenantService holds the tenant-scoped business RPCs that the generic
// rest/v3 CRUD on sys_tenants cannot express: the global tenant
// dropdown and the per-tenant info read.  Tenant rows are global (the
// model carries no tenant_id column), so every RPC here is
// cross-tenant by design; access control is the caller's
// responsibility (see admin/README.md).
type TenantServiceHttpServer interface {
	// Global tenant dropdown.  Wire format: GET /tenant/options.
	ListTenantOptions(ctx context.Context, req *Empty) (res *ListTenantOptionsResponse, err error)
	// Tenant info by id, for UI display.  Wire format:
	// GET /tenant/detail?id={id}.
	Tenant(ctx context.Context, req *TenantRequest) (res *TenantInfo, err error)
}

// TenantService server wrapper
type tenantServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server TenantServiceHttpServer
}

func (s *tenantServiceServerWrapper) wrapHttpTenantServiceListTenantOptions(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.ListTenantOptions(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *tenantServiceServerWrapper) wrapHttpTenantServiceTenant(ctx *http.Context) (err error) {
	req := &TenantRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.Tenant(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterTenantServiceRouter(hs *http.Server, s TenantServiceHttpServer, opts ...http.RouteOption) {
	is := &tenantServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register TenantService.ListTenantOptions http handler
	hs.GET("/tenant/options", is.wrapHttpTenantServiceListTenantOptions)
	// register TenantService.Tenant http handler
	hs.GET("/tenant/detail", is.wrapHttpTenantServiceTenant)
}
