// Code generated by protoc-gen-go-aeus. DO NOT EDIT.
// source: user.proto
package pb

import (
	"context"
	"github.com/sjlit/aeus/pkg/errs"
	"github.com/sjlit/aeus/transport/http"
)

// UserService holds the per-user business RPCs that the generic rest/v3
// CRUD on sys_users cannot express: profile read/update, password change /
// admin reset, avatar URL, and the permission-derived menus/permission
// codes the SPA needs to render the side bar and the per-button guards.
//
// Caller identity is taken from the JWT claims in ctx (see
// middleware/auth); requests intentionally do NOT carry target_uid for
// self-targeted RPCs.
type UserServiceHttpServer interface {
	Profile(ctx context.Context, req *Empty) (res *UserProfile, err error)

	UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (res *UserProfile, err error)

	ChangePassword(ctx context.Context, req *ChangePasswordRequest) (res *Empty, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordRequest) (res *ResetPasswordResponse, err error)

	SetAvatarByURL(ctx context.Context, req *SetAvatarByURLRequest) (res *SetAvatarByURLResponse, err error)

	ListVisibleMenus(ctx context.Context, req *Empty) (res *ListVisibleMenusResponse, err error)

	ListPermissionCodes(ctx context.Context, req *Empty) (res *ListPermissionCodesResponse, err error)
}

// UserService server wrapper
type userServiceServerWrapper struct {
	http   *http.Server
	opts   *http.RouteOptions
	server UserServiceHttpServer
}

func (s *userServiceServerWrapper) wrapHttpUserServiceProfile(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.Profile(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceUpdateProfile(ctx *http.Context) (err error) {
	req := &UpdateProfileRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.UpdateProfile(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceChangePassword(ctx *http.Context) (err error) {
	req := &ChangePasswordRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.ChangePassword(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceResetPassword(ctx *http.Context) (err error) {
	req := &ResetPasswordRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.ResetPassword(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceSetAvatarByURL(ctx *http.Context) (err error) {
	req := &SetAvatarByURLRequest{}
	if err := ctx.Bind(req); err != nil {
		return ctx.Error(int(errs.CodeInvalid), err.Error())
	}
	if res, err := s.server.SetAvatarByURL(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceListVisibleMenus(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.ListVisibleMenus(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}

func (s *userServiceServerWrapper) wrapHttpUserServiceListPermissionCodes(ctx *http.Context) (err error) {
	req := &Empty{}
	if res, err := s.server.ListPermissionCodes(ctx.Context(), req); err != nil {
		if er, ok := err.(*errs.Error); ok {
			return ctx.Error(int(er.Code), er.Message)
		} else {
			return ctx.Error(int(errs.CodeUnavailable), err.Error())
		}
	} else {
		return ctx.Success(res)
	}
}
func RegisterUserServiceRouter(hs *http.Server, s UserServiceHttpServer, opts ...http.RouteOption) {
	is := &userServiceServerWrapper{http: hs, server: s}
	is.opts = http.NewRouteOptions(opts...)
	// register UserService.Profile http handler
	hs.GET("/user/profile", is.wrapHttpUserServiceProfile)
	// register UserService.UpdateProfile http handler
	hs.PATCH("/user/profile", is.wrapHttpUserServiceUpdateProfile)
	// register UserService.ChangePassword http handler
	hs.POST("/user/change-password", is.wrapHttpUserServiceChangePassword)
	// register UserService.ResetPassword http handler
	hs.POST("/user/reset-password", is.wrapHttpUserServiceResetPassword)
	// register UserService.SetAvatarByURL http handler
	hs.POST("/user/set-avatar", is.wrapHttpUserServiceSetAvatarByURL)
	// register UserService.ListVisibleMenus http handler
	hs.GET("/user/menus", is.wrapHttpUserServiceListVisibleMenus)
	// register UserService.ListPermissionCodes http handler
	hs.GET("/user/permissions", is.wrapHttpUserServiceListPermissionCodes)
}
