// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfile is the flattened wire view of the caller's sys_users row.
// role is the Role.Key, dept_id the owning department.
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	DeptId        int64                  `protobuf:"varint,8,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

// UpdateProfileRequest is a partial update of the caller's profile:
// username/email/gender are applied only when non-empty; description is
// always applied (send "" to clear it).
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ChangePasswordRequest changes the caller's own password; old_password
// must match the current one.
type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ResetPasswordRequest resets another user's password (admin-only:
// the caller's role must be a super-admin role).
type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     string                 `protobuf:"bytes,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordRequest) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ResetPasswordResponse echoes the uid whose password was reset.
type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     string                 `protobuf:"bytes,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPasswordResponse) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

// SetAvatarByURLRequest stores an avatar URL for the caller. The URL
// must be non-empty and fit models.User.Avatar (size 1024).
type SetAvatarByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvatarByURLRequest) Reset() {
	*x = SetAvatarByURLRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvatarByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvatarByURLRequest) ProtoMessage() {}

func (x *SetAvatarByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvatarByURLRequest.ProtoReflect.Descriptor instead.
func (*SetAvatarByURLRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *SetAvatarByURLRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// SetAvatarByURLResponse echoes the stored avatar URL.
type SetAvatarByURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvatarByURLResponse) Reset() {
	*x = SetAvatarByURLResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvatarByURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvatarByURLResponse) ProtoMessage() {}

func (x *SetAvatarByURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvatarByURLResponse.ProtoReflect.Descriptor instead.
func (*SetAvatarByURLResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *SetAvatarByURLResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// MenuEntry is intentionally flat: the frontend reconstructs the tree from
// parent so a single RPC returns the whole visible subtree. parent mirrors
// models.Menu.Parent (string name, not numeric FK). title is duplicated
// from name for the common case where a frontend wants a display label
// without re-mapping the row.
//
// view_path is the auto-derived "@/views/<module>/<singular-table>/Index.vue"
// populated by Server.fillDerivedSpec at Setup time.  Empty means the
// operator has not provided one and the frontend should fall back to its
// own static mapping table for legacy components.
type MenuEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Parent        string                 `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Public        bool                   `protobuf:"varint,6,opt,name=public,proto3" json:"public,omitempty"`
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`
	ViewPath      string                 `protobuf:"bytes,8,opt,name=view_path,json=viewPath,proto3" json:"view_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuEntry) Reset() {
	*x = MenuEntry{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuEntry) ProtoMessage() {}

func (x *MenuEntry) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuEntry.ProtoReflect.Descriptor instead.
func (*MenuEntry) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *MenuEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuEntry) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MenuEntry) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *MenuEntry) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuEntry) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *MenuEntry) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MenuEntry) GetViewPath() string {
	if x != nil {
		return x.ViewPath
	}
	return ""
}

// ListVisibleMenusResponse is the flat list of menus visible to the
// caller's role (see MenuEntry); the frontend rebuilds the tree.
type ListVisibleMenusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Menus         []*MenuEntry           `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisibleMenusResponse) Reset() {
	*x = ListVisibleMenusResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisibleMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisibleMenusResponse) ProtoMessage() {}

func (x *ListVisibleMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisibleMenusResponse.ProtoReflect.Descriptor instead.
func (*ListVisibleMenusResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListVisibleMenusResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListVisibleMenusResponse) GetMenus() []*MenuEntry {
	if x != nil {
		return x.Menus
	}
	return nil
}

// ListPermissionCodesResponse carries the API permission codes
// (Permission.Data) granted to the caller's role.
type ListPermissionCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionCodesResponse) Reset() {
	*x = ListPermissionCodesResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionCodesResponse) ProtoMessage() {}

func (x *ListPermissionCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionCodesResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionCodesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListPermissionCodesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPermissionCodesResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\xd0\x01\n" +
	"\vUserProfile\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x17\n" +
	"\adept_id\x18\b \x01(\x03R\x06deptId\"\x82\x01\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"X\n" +
	"\x14ResetPasswordRequest\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x01 \x01(\tR\ttargetUid\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"6\n" +
	"\x15ResetPasswordResponse\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x01 \x01(\tR\ttargetUid\"6\n" +
	"\x15SetAvatarByURLRequest\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\"7\n" +
	"\x16SetAvatarByURLResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\"\xc8\x01\n" +
	"\tMenuEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\tR\x06parent\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x16\n" +
	"\x06public\x18\x06 \x01(\bR\x06public\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hidden\x12\x1b\n" +
	"\tview_path\x18\b \x01(\tR\bviewPath\"`\n" +
	"\x18ListVisibleMenusResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\x05menus\x18\x02 \x03(\v2\r.pb.MenuEntryR\x05menus\"`\n" +
	"\x1bListPermissionCodesResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions2\xac\x05\n" +
	"\vUserService\x12I\n" +
	"\aProfile\x12\x16.google.protobuf.Empty\x1a\x0f.pb.UserProfile\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/user/profile\x12T\n" +
	"\rUpdateProfile\x12\x18.pb.UpdateProfileRequest\x1a\x0f.pb.UserProfile\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*2\r/user/profile\x12e\n" +
	"\x0eChangePassword\x12\x19.pb.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/user/change-password\x12e\n" +
	"\rResetPassword\x12\x18.pb.ResetPasswordRequest\x1a\x19.pb.ResetPasswordResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/reset-password\x12d\n" +
	"\x0eSetAvatarByURL\x12\x19.pb.SetAvatarByURLRequest\x1a\x1a.pb.SetAvatarByURLResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/user/set-avatar\x12]\n" +
	"\x10ListVisibleMenus\x12\x16.google.protobuf.Empty\x1a\x1c.pb.ListVisibleMenusResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/user/menus\x12i\n" +
	"\x13ListPermissionCodes\x12\x16.google.protobuf.Empty\x1a\x1f.pb.ListPermissionCodesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/user/permissionsB#Z!github.com/sjlit/aeus/admin/pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(*UserProfile)(nil),                 // 0: pb.UserProfile
	(*UpdateProfileRequest)(nil),        // 1: pb.UpdateProfileRequest
	(*ChangePasswordRequest)(nil),       // 2: pb.ChangePasswordRequest
	(*ResetPasswordRequest)(nil),        // 3: pb.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),       // 4: pb.ResetPasswordResponse
	(*SetAvatarByURLRequest)(nil),       // 5: pb.SetAvatarByURLRequest
	(*SetAvatarByURLResponse)(nil),      // 6: pb.SetAvatarByURLResponse
	(*MenuEntry)(nil),                   // 7: pb.MenuEntry
	(*ListVisibleMenusResponse)(nil),    // 8: pb.ListVisibleMenusResponse
	(*ListPermissionCodesResponse)(nil), // 9: pb.ListPermissionCodesResponse
	(*emptypb.Empty)(nil),               // 10: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	7,  // 0: pb.ListVisibleMenusResponse.menus:type_name -> pb.MenuEntry
	10, // 1: pb.UserService.Profile:input_type -> google.protobuf.Empty
	1,  // 2: pb.UserService.UpdateProfile:input_type -> pb.UpdateProfileRequest
	2,  // 3: pb.UserService.ChangePassword:input_type -> pb.ChangePasswordRequest
	3,  // 4: pb.UserService.ResetPassword:input_type -> pb.ResetPasswordRequest
	5,  // 5: pb.UserService.SetAvatarByURL:input_type -> pb.SetAvatarByURLRequest
	10, // 6: pb.UserService.ListVisibleMenus:input_type -> google.protobuf.Empty
	10, // 7: pb.UserService.ListPermissionCodes:input_type -> google.protobuf.Empty
	0,  // 8: pb.UserService.Profile:output_type -> pb.UserProfile
	0,  // 9: pb.UserService.UpdateProfile:output_type -> pb.UserProfile
	10, // 10: pb.UserService.ChangePassword:output_type -> google.protobuf.Empty
	4,  // 11: pb.UserService.ResetPassword:output_type -> pb.ResetPasswordResponse
	6,  // 12: pb.UserService.SetAvatarByURL:output_type -> pb.SetAvatarByURLResponse
	8,  // 13: pb.UserService.ListVisibleMenus:output_type -> pb.ListVisibleMenusResponse
	9,  // 14: pb.UserService.ListPermissionCodes:output_type -> pb.ListPermissionCodesResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
