// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: mcp/mcp.proto

package mcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type McpMessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpMessageOptions) Reset() {
	*x = McpMessageOptions{}
	mi := &file_mcp_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpMessageOptions) ProtoMessage() {}

func (x *McpMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpMessageOptions.ProtoReflect.Descriptor instead.
func (*McpMessageOptions) Descriptor() ([]byte, []int) {
	return file_mcp_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *McpMessageOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpMessageOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *McpMessageOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_mcp_mcp_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*McpMessageOptions)(nil),
		Field:         52120,
		Name:          "aeus.mcp",
		Tag:           "bytes,52120,opt,name=mcp",
		Filename:      "mcp/mcp.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional aeus.McpMessageOptions mcp = 52120;
	E_Mcp = &file_mcp_mcp_proto_extTypes[0]
)

var File_mcp_mcp_proto protoreflect.FileDescriptor

const file_mcp_mcp_proto_rawDesc = "" +
	"\n" +
	"\rmcp/mcp.proto\x12\x04aeus\x1a google/protobuf/descriptor.proto\"_\n" +
	"\x11McpMessageOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription:K\n" +
	"\x03mcp\x12\x1e.google.protobuf.MethodOptions\x18\x98\x97\x03 \x01(\v2\x17.aeus.McpMessageOptionsR\x03mcpB(Z&github.com:sjlit/aeus/pkg/proto/mcpb\x06proto3"

var (
	file_mcp_mcp_proto_rawDescOnce sync.Once
	file_mcp_mcp_proto_rawDescData []byte
)

func file_mcp_mcp_proto_rawDescGZIP() []byte {
	file_mcp_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_mcp_proto_rawDesc), len(file_mcp_mcp_proto_rawDesc)))
	})
	return file_mcp_mcp_proto_rawDescData
}

var file_mcp_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_mcp_proto_goTypes = []any{
	(*McpMessageOptions)(nil),          // 0: aeus.McpMessageOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_mcp_mcp_proto_depIdxs = []int32{
	1, // 0: aeus.mcp:extendee -> google.protobuf.MethodOptions
	0, // 1: aeus.mcp:type_name -> aeus.McpMessageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_mcp_proto_init() }
func file_mcp_mcp_proto_init() {
	if File_mcp_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_mcp_proto_rawDesc), len(file_mcp_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mcp_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_mcp_proto_depIdxs,
		MessageInfos:      file_mcp_mcp_proto_msgTypes,
		ExtensionInfos:    file_mcp_mcp_proto_extTypes,
	}.Build()
	File_mcp_mcp_proto = out.File
	file_mcp_mcp_proto_goTypes = nil
	file_mcp_mcp_proto_depIdxs = nil
}
